# -*- coding: utf-8 -*-
"""get_items.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XltsfYqm40ob_8168WeMsatl4P7dW08n
"""

import pandas as pd
def process_dataframe(input_text, num_rows=6):
    # Load the DataFrame from the URL
    df2 = pd.read_json('https://query.data.world/s/nuovlv2dfk425weukkmncb3aqfqb46?dws=00000')

    # Split the input text into words
    split_words = input_text.split()
    colour = split_words[0]
    name = split_words[1]

    # Filter rows based on the name in the title
    filtered = df2[df2['title'].apply(lambda title: name in title.split())]

    # Filter rows based on color if specified, otherwise show all
    if colour != 'any':
        extracted_colors = []
        for dicts in filtered['product_details']:
            color_found = False
            for d in dicts:
                if 'Color' in d:
                    extracted_colors.append(d['Color'])
                    color_found = True
                    break
            if not color_found:
                extracted_colors.append(None)
        filtered['extracted_color'] = extracted_colors
        filtered.dropna(subset=['extracted_color'], inplace=True)
        filtered = filtered[filtered['extracted_color'].str.contains(colour, case=False)]

    # Show the first num_rows rows
    output = filtered.head(num_rows)

    return output

# Example usage
input_text = 'blue Trousers'
output = process_dataframe(input_text)

import json

output = output.reset_index(drop=True)
output_list=[]
for i in range(1, 5):
    temp_dict = {}  # Use a different name for the dictionary variable
    temp_dict["actual_price"] = output.at[i, "actual_price"]
    temp_dict["average_rating"] = output.at[i, "average_rating"]
    temp_dict["brand"] = output.at[i, "brand"]
    temp_dict["description"] = output.at[i, "description"]
    temp_dict["discount"] = output.at[i, "discount"]
    temp_dict["images"] = output.at[i, "images"]
    temp_dict["product_details"] = output.at[i, "product_details"]
    temp_dict["title"] = output.at[i, "title"]
    temp_dict["url"] = output.at[i, "url"]
    # print(temp_dict)
    output_list.append(temp_dict)

print(json.dumps(output_list, indent=4))




   